name: aisdk
description: AI SDK for Dart and Flutter
version: 0.0.1
repository: https://github.com/elias8/aisdk

environment:
  sdk: ^3.7.0

dependencies:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
